  name: CI
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Install npm modules
      run: npm install
    - name: Run ESLint
      run: npm run lint